# Generated by Django 6.0.6 on 2026-07-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='post_media/')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostPlatformStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_statuses', to='posts.post')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_accounts.socialaccount')),
            ],
            options={
                'unique_together': {('post', 'social_account')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='social_accounts',
            field=models.ManyToManyField(related_name='posts', through='posts.PostPlatformStatus', to='social_accounts.socialaccount'),
        ),
    ]
