# Generated by Django 6.0.6 on 2026-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='platform_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
