# Generated by Django 6.0.6 on 2026-07-27 19:05

import posts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, storage=posts.storage.AutoMediaCloudinaryStorage(), upload_to='post_media/'),
        ),
    ]
