# Generated by Django 6.0.6 on 2026-07-10 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_error_message_post_platform_post_id'),
        ('social_accounts', '0004_socialaccount_whatsapp_business_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platform_post_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='social_account',
        ),
        migrations.CreateModel(
            name='PostPlatformStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_statuses', to='posts.post')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_accounts.socialaccount')),
            ],
            options={
                'unique_together': {('post', 'social_account')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='social_accounts',
            field=models.ManyToManyField(related_name='posts', through='posts.PostPlatformStatus', to='social_accounts.socialaccount'),
        ),
    ]
