# Generated by Django 6.0.6 on 2026-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postplatformstatus',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='scheduled', max_length=20),
        ),
    ]
