# Generated by Django 6.0.6 on 2026-08-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_media_file_remove_post_media_type_and_more'),
        ('social_accounts', '0003_socialaccount_permitted_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('external_post_id', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('permalink_url', models.URLField(blank=True, max_length=500, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_posts', to='social_accounts.socialaccount')),
            ],
            options={
                'ordering': ['-posted_at'],
                'unique_together': {('social_account', 'external_post_id')},
            },
        ),
    ]
