# Generated by Django 6.0.6 on 2026-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_externalpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpost',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalpost',
            name='permalink_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
