# Generated by Django 6.0.6 on 2026-08-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_externalpost_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('threads', 'Threads'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
