# Generated by Django 6.0.6 on 2026-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_externalpost_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
