# Generated by Django 6.0.6 on 2026-09-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('posts', '0010_postmedia_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.organization'),
        ),
    ]
