# Generated by Django 6.0.6 on 2026-07-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
        ('social_accounts', '0002_alter_socialaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxitem',
            options={'ordering': ['-received_at']},
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='sender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='social_accounts.socialaccount'),
        ),
    ]
