# Generated by Django 6.0.6 on 2026-07-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('gmail', 'Gmail')], max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('account_username', models.CharField(blank=True, max_length=100)),
                ('platform_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('_access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform'],
                'unique_together': {('platform', 'platform_account_id')},
            },
        ),
    ]
