# Generated by Django 6.0.6 on 2026-07-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='platform_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
