# Generated by Django 6.0.6 on 2026-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0002_socialaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, db_column='access_token', null=True),
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='access_token',
            new_name='_access_token',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, db_column='refresh_token', null=True),
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='refresh_token',
            new_name='_refresh_token',
        ),
    ]
