# Generated by Django 6.0.6 on 2026-07-18 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0002_alter_socialaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='permitted_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
