# Generated by Django 6.0.6 on 2026-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0003_alter_socialaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter / X')], max_length=20),
        ),
    ]
