# Generated by Django 6.0.6 on 2026-09-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('social_accounts', '0003_socialaccount_permitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='organizations.organization'),
        ),
    ]
