# Generated by Django 6.0.6 on 2026-07-10 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0004_socialaccount_whatsapp_business_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['platform']},
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('platform', 'platform_account_id')},
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='connected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('threads', 'Threads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('gmail', 'Gmail')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='team',
        ),
    ]
