# Generated by Django 6.0.6 on 2026-07-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20, null=True),
        ),
    ]
