# Generated by Django 6.0.6 on 2026-07-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='permitted_accounts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
