# Generated by Django 6.0.6 on 2026-08-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation_permitted_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
