# Generated by Django 6.0.6 on 2026-08-14 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customusermodel_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('password_changed', 'Password Changed'), ('permission_updated', 'Permission Updated'), ('post_created', 'Post Created'), ('post_published', 'Post Published'), ('post_edited', 'Post Edited'), ('post_deleted', 'Post Deleted'), ('post_failed', 'Post Failed'), ('account_connected', 'Account Connected'), ('account_disconnected', 'Account Disconnected'), ('inbox_replied', 'Inbox Replied'), ('inbox_marked_read', 'Inbox Marked Read'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted')], max_length=50)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx')],
            },
        ),
    ]
